---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cu-du-cluster-qa-new-bangalore-du-03-n3k
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '80'
spec:
  # The project the application belongs to.
  project: default
  destination:
    name: ''
    #namespace: ''
    #server: 'https://172.29.231.140:6443'
    server: 'https://api.cu-du-cluster-qa-new.rtp.raleigh.ibm.com:6443'
  # Source of the application manifests
  source:
    repoURL: 'https://github.com/traghave123/vran-manifests.git'
    targetRevision: HEAD
    path: ran-manifests/manifests/cu-du-cluster-qa-new/bangalore/dell/du/03-n3000/03-n3k
    directory:
      recurse: false
  # Sync policy
  syncPolicy:
    automated: 
      prune: false
      selfHeal: true 
      allowEmpty: false
    syncOptions:
      # (equivalent to 'kubectl apply --validate=true')
      - Validate=false
      - CreateNamespace=true
    retry:
      # unlimited if less than 0
      limit: -1
      backoff:
        # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        duration: 5s
        # a factor to multiply the base duration after each failed retry
        factor: 2
        # the maximum amount of time allowed for the backoff strategy
        maxDuration: 3m