---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ran-du-bangalore-server-profile-du-dell-r640-00

commonAnnotations:
 #argocd.argoproj.io/sync-wave: "20"
 argocd.argoproj.io/sync-options: Prune=false
 argocd.argoproj.io/compare-options: IgnoreExtraneous
# Apps of Apps
resources:
  - 40-cu-du-cluster-qa-new-bangalore-dell-du.yaml
  - 50-cu-du-cluster-qa-new-bangalore-dell-du-00-pre.yaml
  - 60-cu-du-cluster-qa-new-bangalore-dell-du-01-post.yaml
  - 70-cu-du-cluster-qa-new-bangalore-dell-du-02-configs.yaml
  - 80-cu-du-cluster-qa-new-bangalore-dell-du-03-n3k.yaml
  - 90-cu-du-cluster-qa-new-bangalore-dell-du-n3k-sriov.yaml
  - 100-cu-du-cluster-qa-new-bangalore-dell-du-n3k-cluster.yaml
  - 110-cu-du-cluster-qa-new-bangalore-dell-du-sriovfec-clusterconfig.yaml
