---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: n3000-subscription
  namespace: vran-acceleration-operators
spec:
  channel: stable
  name: n3000
  source: "vran-automation-certified-operator-catalog"
  sourceNamespace: openshift-marketplace