---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ran-cu-bangalore-server-profile-cu-dell-r640-00

commonAnnotations:
 #argocd.argoproj.io/sync-wave: "20"
 argocd.argoproj.io/sync-options: Prune=false
 argocd.argoproj.io/compare-options: IgnoreExtraneous
# Apps of Apps
resources:
  - 40-cu-du-cluster-qa-new-bangalore-dell-cu.yaml
  - 50-cu-du-cluster-qa-new-bangalore-dell-cu-00-pre.yaml
  - 60-cu-du-cluster-qa-new-bangalore-dell-cu-01-post.yaml
  - 70-cu-du-cluster-qa-new-bangalore-dell-cu-02-virt.yaml
  - 80-cu-du-cluster-qa-new-bangalore-dell-cu-02-settings.yaml
