---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  cluster: cu-du-cluster-qa-new
  topology.kubernetes.io/region: cu-du-cluster-qa-new
  # Each SITE_ID is a different zone


bases:
  # Import base cluster definition
  - ./base/ran-bases
  - ./base/ran-resources
  - ./base/ran-cu
  - ./base/ran-du