---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ran-du-bangalore-server-profile-du-dell-r640-00
  
commonAnnotations:  
  argocd.argoproj.io/sync-options: Prune=false
  argocd.argoproj.io/compare-options: IgnoreExtraneous  

resources:
  - 00-hook-mcp-wait-job-bangalore.yaml
  - 01-disable-chronyd-ran-du-bangalore-server-profile-du-dell-r640-00.yaml
  
  - 02-tuned-ran-du-bangalore-server-profile-du-dell-r640-00.yaml
  - 03-mc-fixrps-ran-du-bangalore-server-profile-du-dell-r640-00-pao-profile-du-dell-r640-00.yaml
