---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ran-cu-bangalore-server-profile-cu-dell-r640-00

resources:
  # SRIOV Configs
  - 00-hook-mcp-wait-job-bangalore.yaml
  - 00-bangalore-sriov-namespace.yaml
  - 00-bangalore-sriov-node-policy.yaml
  - 01-bangalore-sriov-networks.yaml
